# This file reads in the text file generated by compare_peaks_recalc.R
# and plots two basic histograms to get peak distributions

# read in the file
x <- read.table("Peaks_file_recalc.txt",as.is=T,header=T)

# Calculate the peak size based on x
y <- data.frame(peak.size = x$Right.peak-x$Left.peak,
                Model.size = x$Right.model-x$Left.model)

lattice_size<-161 # change this for lattice size

# Compute model peak size based on lattice size
y$Model.size <- y$Model.size * lattice_size
Model.peaks <- sum(!is.na(y$Model.size))
y$Model.size[y$Model.size<200] <- NA

# Output histogram as a PNG file
png("histograms.png")

# Histograms are plotted with a bin width equal to lattice_size to prevent
# aliases for Model peak size distribution
hist(y$peak.size,prob=TRUE,xlim=c(0,15000),
     breaks=seq(from=0,to=lattice_size*1e4,by=lattice_size),
     ylim=c(0,0.002),col="#FF000030",main="Peak size histogram",xlab="Peak size (bp)")
hist(y$Model.size,prob=TRUE,
     breaks=seq(from=0,to=lattice_size*1e4,by=lattice_size),col="#00FF0030",add=T)


legend("topright",
       c("Data peaks","Model peaks"),
       lty=0,
       fill=c("#FF000030","#00FF0030"))

dev.off()

# Output a zoomed (on the y-axis) histogram as a PNG file
png("histograms.zoom.png")

# Histograms are plotted with a bin width equal to lattice_size to prevent
# aliases for Model peak size distribution
hist(y$peak.size,prob=TRUE,xlim=c(0,15000),
     breaks=seq(from=0,to=lattice_size*1e4,by=lattice_size),
     ylim=c(0,0.00025),col="#FF000030",main="Peak size histogram",xlab="Peak size (bp)")
hist(y$Model.size,prob=TRUE,
     breaks=seq(from=0,to=lattice_size*1e4,by=lattice_size),col="#00FF0030",add=T)
legend("topright",
       c("Data peaks","Model peaks"),
       lty=0,
       fill=c("#FF000030","#00FF0030"))

dev.off()

# Output lists of peaks to text files which could be used to generate other histograms
write.table(y$Model.size[!is.na(y$Model.size)],file="model_peaks.txt",col.names=F,row.names=F)
write.table(y$peak.size[!is.na(y$peak.size)],file="MACS2_peaks.txt",col.names=F,row.names=F)
